# Generated by Django 4.2.1 on 2023-05-27 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
