# Generated by Django 4.2.1 on 2023-07-24 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('director', models.CharField(max_length=250)),
                ('writer', models.CharField(max_length=250)),
                ('stars', models.CharField(max_length=250)),
                ('storyline', models.TextField()),
                ('genres', models.CharField(max_length=250)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('countries_of_origin', models.CharField(blank=True, max_length=250, null=True)),
                ('language', models.CharField(max_length=250)),
                ('filming_locations', models.CharField(max_length=250)),
                ('production_companies', models.CharField(max_length=250)),
                ('budget', models.IntegerField()),
                ('gross_worldwide', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
