# Generated by Django 4.2.1 on 2023-09-20 11:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_review', '0002_userreview_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userreview',
            unique_together={('movie', 'user')},
        ),
    ]
